### ISSUE TITLE
ikachan has no z-index

### ISSUE THREAD

**Issue by dotuser** [Xkeeper0/jul#15]
Ikachan, the greatest excuse for a major bugfix, is lacking a z-index now. Formerly he would appear above most post layouts but now apparently likes to sneak in behind them, making him disappear.

Mostly silly really, but still something that at some point may want to be corrected.

**Comment by Xkeeper0** [comment]
https://github.com/Xkeeper0/jul/blob/master/lib/layout.php#L346
