### ISSUE TITLE
&mood&

### ISSUE THREAD

**Issue by Sanqui** [Xkeeper0/jul#17]
A tag for the post mood number.  Would enable layouts with pictures or colors changing according to the post mood, not just the avatar.

I remember trying to do it myself years ago and having some issues, but it should be possible.  Note that it needs to update when you edit the post.

**Comment by Xkeeper0** [comment]
Might just make this one of the parameters passed from $userdata, since it's already included in every post. Updating it will be interesting, though.

**Comment by Xkeeper0** [comment]
Actually looking into this now (only 5 years late, lol): I think this would require changing how the tags system works, at least on some level. There's no tags that, iirc, work the post itself, just your user state. Level, posts, etc. are all parts of the user, but the only part of the post itself that's given to the tags system is the actual message text... But unlike the rest of the tags, it's not something that needs to be stored indefinitely, as it's still part of the post.

Hmm :/
