### ISSUE TITLE
Option to remove squid.png or at least hide it

### ISSUE THREAD

**Issue by themushmouth** [Xkeeper0/jul#38]
like in the title is it possible for user to remove http://jul.rustedlogic.net/images/squid.png ? I would like it to be hidden at the very least.

**Comment by Sanqui** [comment]
Opposed.  If you hate Ikachan so much, adblock him.  Maybe you'll feel a little bad.

**Comment by rambly** [comment]
make ikachan big.  i want the big squid

**Comment by no-boot-device** [comment]
here's how to fix. 

```
@keyframes hidesquid{
    0% {
        transform: scale(1,1);
    }
    100% {
        transform: scale(500,500);
    }
}

#f_ikachan {
  animation: hidesquid 300s infinite ease-in;
}
```
add this to a user stylesheet. hope this helps
